#!/bin/bash -e

# first target binary name, then options to readwrite
BIN=$1
shift

tmpfile=/tmp/`basename $BIN`
IMPACT=$HOME/Xilinx/ISE_DS/ISE/bin/lin64/impact

\cd $HOME/hwex/tools
source $HOME/Xilinx/ISE_DS/settings64.sh >/dev/null 2>/dev/null
export XILINXD_LICENSE_FILE=2100@133.11.27.150
$IMPACT -batch mimic.impact.cmd > /dev/null 2>/dev/null
\cd - > /dev/null
cut -f1 $BIN > $tmpfile
$HOME/programs/cpu/io_program/readwrite $* -d $tmpfile
