#!/bin/bash -e

# first target binary name, then options to readwrite
BIN=$1
shift

tmpfile=/tmp/`basename $BIN`
IMPACT=$HOME/Xilinx/ISE_DS/ISE/bin/lin64/impact

runner_dir=$(dirname $0)

# before export xilinx libraries
\cd $runner_dir/rs232c_io && make && \cd - > /dev/null

\cd $HOME/hwex/tools
source $HOME/Xilinx/ISE_DS/settings64.sh >/dev/null 2>/dev/null
export XILINXD_LICENSE_FILE=2100@133.11.27.150
$IMPACT -batch mimic.impact.cmd > /dev/null 2>/dev/null
\cd - > /dev/null
cut -f1 $BIN > $tmpfile
$runner_dir/rs232c_io/readwrite $* -d $tmpfile
