#!/bin/sh -ex

# Makefile: http://repo.or.cz/w/zpu/zpuino.git/blob_plain/942cbb483bd12adf1abaeeafec52ea29b24d52b6:/zpu/hdl/zpuino/boards/papilio-one/s3e500/Makefile

TITLE=mimic
PROJECT_DIR=/home/tomita/programs/cpu/mips
revision=`cd $PROJECT_DIR; git rev-parse --short HEAD`
branch=`cd $PROJECT_DIR; git rev-parse --abbrev-ref HEAD`
BITNAME=${TITLE}_${branch}_${revision}_`date '+%s'`
TOP=top
UCF=$PROJECT_DIR/2nd/top.ucf

if [ $# = 0 ]; then

  ruby > initial_text.dat <<EOF
WIDTH=80
HEIGHT=30
lines=[" "*WIDTH]*HEIGHT
lines[0]="Waiting program...".ljust(WIDTH)
lines[HEIGHT-2]="Kandouhan #{Time.now.month}/#{Time.now.day}".rjust(WIDTH)
lines[HEIGHT-1]="$BITNAME".rjust(WIDTH)
lines.join.gsub(' ',  "\0").each_char{|c| puts c.ord.to_s(2).rjust(7,"0") }
EOF

  grep wtime $PROJECT_DIR/2nd/top.vhd | grep "0099" ||
    (echo "Have you set synthesize mode? RS232C wtime is awkward."; exit 1)

  xst -intstyle ise -filter "iseconfig/filter.filter" -ifn "$TOP.xst" -ofn "$TOP.syr"
  ngdbuild -filter "iseconfig/filter.filter" -intstyle ise -dd _ngo -sd ipcore_dir -nt timestamp -uc $UCF -p xc5vlx50t-ff1136-1 $TOP.ngc $TOP.ngd
  map -filter "iseconfig/filter.filter" -intstyle ise -p xc5vlx50t-ff1136-1 -w -logic_opt off -ol high -t 1 -register_duplication off -global_opt off -mt off -cm area -ir off -pr off -lc off -power off -o $TOP_map.ncd $TOP.ngd $TOP.pcf
  par -filter "iseconfig/filter.filter" -w -intstyle ise -ol high -mt off $TOP_map.ncd $TOP.ncd $TOP.pcf
  trce -filter iseconfig/filter.filter -intstyle ise -v 3 -s 1 -n 3 -fastpaths -xml $TOP.twx $TOP.ncd -o $TOP.twr $TOP.pcf
  bitgen -filter "iseconfig/filter.filter" -intstyle ise -f $TOP.ut $TOP.ncd

fi

\cat > $TITLE.impact.cmd <<EOF
setMode -bs
setCable -port auto
Identify -inferir
identifyMPM
assignFile -p 2 -file $BITNAME.bit
Program -p 2
quit
EOF

rsync $TOP.bit is:hwex/tools/$BITNAME.bit
rsync $TITLE.impact.cmd is:hwex/tools/$TITLE.impact.cmd

ssh is ". ~/hwex/tools/use-ise.sh && cd hwex/tools && impact -batch $TITLE.impact.cmd"
