#!/bin/sh -e

arg=$1
base=`basename $arg`
root_log="$base"_simulation.log
ext=${arg##*.}

if [ $ext = "bin" ]; then
  bin=$arg
else
  if [ -f $arg.ml ]; then
    make $arg.bin_f
  elif [ -f $arg.s ]; then
    assembler/assembler $arg.s $arg.bin
  fi
  simulator/simulator $arg.bin > $root_log

  bin="$arg.bin"
fi

echo "file copy"
cut -f1 $bin > ../instruction.dat
