////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 14.1
//  \   \         Application : xaw2verilog
//  /   /         Filename : my_dcm.v
// /___/   /\     Timestamp : 12/03/2012 09:47:36
// \   \  /  \
//  \___\/\___\
//
//Command: xaw2verilog -intstyle /home/tomita/tmp/mimic/ipcore_dir/my_dcm.xaw -st my_dcm.v
//Design Name: my_dcm
//Device: xc5vlx50t-1ff1136
//
// Module my_dcm
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Period Jitter (unit interval) for block DCM_ADV_INST = 0.017 UI
// Period Jitter (Peak-to-Peak) for block DCM_ADV_INST = 0.206 ns
`timescale 1ns / 1ps

module my_dcm(input CLKIN_IN,
                input RST_IN,
                output CLK_MAIN_OUT,
                output CLK_100_OUT);

   wire CLKFB_IN;
   wire CLK_MAIN_BUF;
   wire CLKIN_IBUFG;
   wire CLK0_BUF;
   wire GND_BIT;
   wire [6:0] GND_BUS_7;
   wire [15:0] GND_BUS_16;

   assign GND_BIT = 0;
   assign GND_BUS_7 = 7'b0000000;
   assign GND_BUS_16 = 16'b0000000000000000;
   assign CLKIN_IBUFG_OUT = CLKIN_IBUFG;
   assign CLK0_OUT = CLKFB_IN;
   BUFG  CLK_MAIN_BUFG_INST (.I(CLK_MAIN_BUF),
                         .O(CLK_MAIN_OUT));
   IBUFG  CLKIN_IBUFG_INST (.I(CLKIN_IN),
                           .O(CLKIN_IBUFG));
   BUFG  CLK0_BUFG_INST (.I(CLK0_BUF),
                        .O(CLKFB_IN));
   DCM_ADV #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(14),
         .CLKFX_MULTIPLY(15), .CLKIN_DIVIDE_BY_2("FALSE"),
         .CLKIN_PERIOD(15.152), .CLKOUT_PHASE_SHIFT("NONE"),
         .DCM_AUTOCALIBRATION("TRUE"), .DCM_PERFORMANCE_MODE("MAX_SPEED"),
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"),
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"),
         .FACTORY_JF(16'hF0F0), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE"),
         .SIM_DEVICE("VIRTEX5") ) DCM_ADV_INST_MAIN (.CLKFB(CLKFB_IN),
                         .CLKIN(CLKIN_IBUFG),
                         .DADDR(GND_BUS_7[6:0]),
                         .DCLK(GND_BIT),
                         .DEN(GND_BIT),
                         .DI(GND_BUS_16[15:0]),
                         .DWE(GND_BIT),
                         .PSCLK(GND_BIT),
                         .PSEN(GND_BIT),
                         .PSINCDEC(GND_BIT),
                         .RST(RST_IN),
                         .CLKDV(),
                         .CLKFX(CLK_MAIN_BUF),
                         .CLKFX180(),
                         .CLK0(CLK0_BUF),
                         .CLK2X(),
                         .CLK2X180(),
                         .CLK90(),
                         .CLK180(),
                         .CLK270(),
                         .DO(),
                         .DRDY(),
                         .LOCKED(),
                         .PSDONE());

   wire CLK_100_BUF;
   wire CLK0_BUF_100;
   wire CLKFB_100_IN;
   BUFG  CLK_MAIN_BUFG_INST_100 (.I(CLK_100_BUF), .O(CLK_100_OUT));
   BUFG  CLK0_BUFG_INST_100 (.I(CLK0_BUF_100), .O(CLKFB_100_IN));
   DCM_ADV #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(2),
         .CLKFX_MULTIPLY(3), .CLKIN_DIVIDE_BY_2("FALSE"),
         .CLKIN_PERIOD(15.15), .CLKOUT_PHASE_SHIFT("NONE"),
         .DCM_AUTOCALIBRATION("TRUE"), .DCM_PERFORMANCE_MODE("MAX_SPEED"),
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"),
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"),
         .FACTORY_JF(16'hF0F0), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE"),
         .SIM_DEVICE("VIRTEX5") ) DCM_ADV_INST_100 (
                         .CLKFB(CLKFB_100_IN),
                         .CLKIN(CLKFB_IN),
                         .DADDR(GND_BUS_7[6:0]),
                         .DCLK(GND_BIT),
                         .DEN(GND_BIT),
                         .DI(GND_BUS_16[15:0]),
                         .DWE(GND_BIT),
                         .PSCLK(GND_BIT),
                         .PSEN(GND_BIT),
                         .PSINCDEC(GND_BIT),
                         .RST(RST_IN),
                         .CLKDV(),
                         .CLKFX(CLK_100_BUF),
                         .CLKFX180(),
                         .CLK0(CLK0_BUF_100),
                         .CLK2X(),
                         .CLK2X180(),
                         .CLK90(),
                         .CLK180(),
                         .CLK270(),
                         .DO(),
                         .DRDY(),
                         .LOCKED(),
                         .PSDONE());
endmodule
